### ISSUE TITLE
Trappist deployment on Rococo

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/trappist#138]
# Trappist deploy on Rococo

### Branch & tag management
Similar to cumulus repository for each release it will be a release branch under the naming convention `polkadot-v<VERSION>` and a tag `v<VERSION>`.

### Release during deployment.
`polkadot-v0.9.37` (XCM v2)

### Srtool 
For generating the release on github with the corresponding attached artifcats for the client and the runtime [srtool](https://github.com/paritytech/srtool) will be used including it's subproject [srtool-actions](https://github.com/chevdor/srtool-actions), which permit to integrate the tool in the a Github action pipeline.

## Runtime versions & upgrades.
Initial runtime version to start: 1000. On every runtime upgrade we can increase the version by 100 and in case of a patch within releases, we can increase by 10. Being:

New runtime version due to new release: 1100
New runtime version due to a patch needed after release 1100: 1110

## Collators

The chain will be set up with two collators in two different cloud instances. 

The deployment of the collators code will be led by the Parity DevOps team.

Both containers will be defined under a `docker.yml` ([Example](https://github.com/paritytech/cumulus/blob/master/docker/docker-compose.yml)) that will be defined in the Trappist repository.

### Sudo / Root Origin
The parachain can be managed by one account that will be granted with the root origin through the Sudo pallet.

### Founded Accounts 
Initially, there will be 6 accounts with 1.5M HOP. (is this enough?)

### HOP tokenomics.
At this point in time there is no emission mechanism for HOP or any defined tokenomics. We should decide what is the most convenient tokenomics for this project. Anyway, i don't see this as a blocker for deployment but something to consider in the near future.

### Council members.

Even if the council is representative from Governance v1, for the purpose of this parachain it still might work as an useful collectives to explore. OpenGov can be a little bit too much for the purpose of this live testnet parachain.

The 6 accounts that were founded during the genesis, will also be set as the council members

### Collator Aura keys

Two keys will be generated using `Sr25519` for the Aura collator keys and they will be provided to the parity DevOps team to deploy.

### Accounts Ownership

All pre funded accounts will be managed and owned by Delivery Services team at Parity.

### trappist_config()
In the `chain_spec/trappist.rs` file for Trappist, there is a new function `trappist_config()` that will contain the "production" configuration for the genesis.

### Parachain Id

The parachain Id for Trappist in Rococo will be ~~**2525**~~ The year that the oldest trappist beer was produced.

### Rockmine
Rename Statemine for Rockmine in XCM config file to keep consistency  across Rococo chain.

### SafeXCMVersion
The parachain will be launched with version 2 so during the next upgrade we can try the migration to version 3 on a live chain.

### Faucet
Pallet Contracts team is looking for use the deployed version of Trappist on Rococo as the chain for education/hackatons workshops ,etc. For this reason i think that we should implement a faucet so users can receive tokens during these activities.

### Task list - 
- [x] Create "Production" like  chain spec for the parachain that will be deployed #140 
- [x] Build a GH action that publish the docker image in the paritytech dockerhub. https://github.com/paritytech/trappist/pull/139
- [ ] Create a GH action that generates a wasm file for the runtime using srtool #134
- [x] Set up benchmarking https://github.com/paritytech/trappist/issues/141
- [x] https://github.com/paritytech/trappist/issues/142
- [x] https://github.com/paritytech/trappist/issues/143
- [x] https://github.com/paritytech/trappist/issues/144
- [x] https://github.com/paritytech/trappist/issues/145
- [x] https://github.com/paritytech/trappist/issues/95
- [x] https://github.com/paritytech/trappist/issues/137
- [ ] https://github.com/paritytech/trappist/issues/146
- [x] https://github.com/paritytech/trappist/issues/152

CC: @stiiifff

**Comment by hbulgarini** [comment]
Needed for deployment: https://github.com/paritytech/devops/issues/2482

**Comment by hbulgarini** [comment]
Keynotes discussion:

- Sudo account will be managed a multisig. The multisig will be set with the 6 pre funded accounts with a 2/6 threshold. It will contain 1 M.
- Council approval with 50% (3 over 6)
- Add a pallet to start into maintenance mode.
- Have a fixed supply of 10 M  and do not make the token inflationary.
- Parachain ID: The year that the oldest trappist beer was produced.
- Implement treasury where it will receive a 80% of tx fees.
- Collators will receive 20% of tx fees.
- In next releases, add democracy pallet. 
- Faucet will be funded manually.
- Add chess pallet so it gets deployed.

**Comment by hbulgarini** [comment]
Parachain deployed and running on Rococo:

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-trappist-rpc.polkadot.io#/explorer

Pending issues to address:
https://github.com/paritytech/trappist/issues/146
https://github.com/paritytech/trappist/issues/242
