### ISSUE TITLE
Add `try_runtime` to Trappist

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/trappist#197]
```[tasklist]
### TODO
- [x] Integrate try-runtime into trappist runtime
- [x] Integrate try-runtime into the node cli
- [ ] Create try-runtime CI workflow for releases
- [x] We will need a node to scrape live state from  an RPC node i.e. [wss://rococo-trappist-rpc.polkadot.io:443](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-trappist-rpc.polkadot.io#/explorer)
- [x] Try-runtime bot
- [ ] Documentation
```

The Polkadot CI for try-runtime is located here:
- https://github.com/paritytech/polkadot/blob/master/scripts/ci/gitlab/pipeline/check.yml#L72-L76

Looks like try-runtime-bot is installed: https://github.com/paritytech/security/issues/12

**Comment by brunopgalvao** [comment]
A try-runtime RPC node has been configured for us: 
- wss://rococo-trappist-try-runtime-node.parity-chains.parity.io:443
- https://cloudflare-ipfs.com/ipns/dotapps.io/?rpc=wss%3A%2F%2Frococo-trappist-try-runtime-node.parity-chains.parity.io#/explorer

Tested with this [PR](https://github.com/paritytech/trappist/pull/239) and it works!
```
./node-try-runtime \
    try-runtime \
    --runtime runtime-try-runtime.wasm \
    -lruntime=debug \
    on-runtime-upgrade \
    live --uri wss://rococo-trappist-try-runtime-node.parity-chains.parity.io:443
2023-06-23 12:16:04.421  INFO main remote-ext: since no at is provided, setting it to latest finalized head, 0xc2136fbc8067ffa76b4da8a888cd1bfbc44d3dc0b468bac5caf4a9895910c3e4    
2023-06-23 12:16:04.424  INFO main remote-ext: since no prefix is filtered, the data for all pallets will be downloaded    
2023-06-23 12:16:04.582  INFO main remote-ext: scraping key-pairs from remote at block height 0xc2136fbc8067ffa76b4da8a888cd1bfbc44d3dc0b468bac5caf4a9895910c3e4    
2023-06-23 12:16:05.766  INFO main remote-ext: Querying a total of 4194 keys from prefix , splitting among 10 threads, 420 keys per thread    
2023-06-23 12:16:07.817  INFO main remote-ext: adding data for hashed prefix: , took 3s    
2023-06-23 12:16:07.817  INFO main remote-ext: adding data for hashed key: 3a636f6465    
2023-06-23 12:16:08.699  INFO main remote-ext: adding data for hashed key: 26aa394eea5630e07c48ae0c9558cef7f9cce9c888469bb1a0dceaa129672ef8    
2023-06-23 12:16:08.833  INFO main remote-ext: adding data for hashed key: 26aa394eea5630e07c48ae0c9558cef702a5c1b19ab7a04f536c519aca4983ac    
2023-06-23 12:16:09.006  INFO main remote-ext: initialized state externalities with storage root 0x3afb36071e9412319f8f4ee222fdee1d8c33bedc11e2df2c7b7e65a7caff0283 and state_version V1    
2023-06-23 12:16:09.735  INFO main try-runtime::cli: original spec: RuntimeString::Owned("trappist-rococo")-1, code hash: a8f35b12ee0829b2e32de13e1bdab6dbeaf59f6ce8b3bc4d749d6cb072e9119d    
2023-06-23 12:16:10.385  INFO main try-runtime::cli: new spec: RuntimeString::Owned("trappist-rococo")-1, code hash: 4d23ca9e9c67d3008e3ff57931d4c0dd7e8640506055baa4c3093cbd4e4e3962    
2023-06-23 12:16:12.609 DEBUG main runtime::frame-support: ✅ no migration for System    
2023-06-23 12:16:12.610  INFO main runtime::frame-support: ⚠️ ParachainSystem declares internal migrations (which *might* execute). On-chain `StorageVersion(2)` vs current storage version `StorageVersion(2)`    
2023-06-23 12:16:12.610 DEBUG main runtime::frame-support: ✅ no migration for RandomnessCollectiveFlip    
2023-06-23 12:16:12.610 DEBUG main runtime::frame-support: ✅ no migration for Timestamp    
2023-06-23 12:16:12.611 DEBUG main runtime::frame-support: ✅ no migration for ParachainInfo    
2023-06-23 12:16:12.611 DEBUG main runtime::frame-support: ✅ no migration for Balances    
2023-06-23 12:16:12.611 DEBUG main runtime::frame-support: ✅ no migration for TransactionPayment    
2023-06-23 12:16:12.611 DEBUG main runtime::frame-support: ✅ no migration for AssetTxPayment    
2023-06-23 12:16:12.611 DEBUG main runtime::frame-support: ✅ no migration for Authorship    
2023-06-23 12:16:12.611 DEBUG main runtime::frame-support: ✅ no migration for CollatorSelection    
2023-06-23 12:16:12.611 DEBUG main runtime::frame-support: ✅ no migration for Session    
2023-06-23 12:16:12.612 DEBUG main runtime::frame-support: ✅ no migration for Aura    
2023-06-23 12:16:12.612 DEBUG main runtime::frame-support: ✅ no migration for AuraExt    
2023-06-23 12:16:12.612  INFO main runtime::frame-support: ⚠️ XcmpQueue declares internal migrations (which *might* execute). On-chain `StorageVersion(2)` vs current storage version `StorageVersion(2)`    
2023-06-23 12:16:12.613  INFO main runtime::frame-support: ⚠️ PolkadotXcm declares internal migrations (which *might* execute). On-chain `StorageVersion(0)` vs current storage version `StorageVersion(0)`    
2023-06-23 12:16:12.613 DEBUG main runtime::frame-support: ✅ no migration for CumulusXcm    
2023-06-23 12:16:12.614  INFO main runtime::frame-support: ⚠️ DmpQueue declares internal migrations (which *might* execute). On-chain `StorageVersion(1)` vs current storage version `StorageVersion(1)`    
2023-06-23 12:16:12.614 DEBUG main runtime::frame-support: ✅ no migration for Contracts    
2023-06-23 12:16:12.614 DEBUG main runtime::frame-support: ✅ no migration for Assets    
2023-06-23 12:16:12.614 DEBUG main runtime::frame-support: ✅ no migration for Identity    
2023-06-23 12:16:12.614 DEBUG main runtime::frame-support: ✅ no migration for Uniques    
2023-06-23 12:16:12.614 DEBUG main runtime::frame-support: ✅ no migration for Scheduler    
2023-06-23 12:16:12.614 DEBUG main runtime::frame-support: ✅ no migration for Preimage    
2023-06-23 12:16:12.615 DEBUG main runtime::frame-support: ✅ no migration for LockdownMode    
2023-06-23 12:16:12.615 DEBUG main runtime::frame-support: ✅ no migration for Utility    
2023-06-23 12:16:12.615 DEBUG main runtime::frame-support: ✅ no migration for Multisig    
2023-06-23 12:16:12.615 DEBUG main runtime::frame-support: ✅ no migration for Council    
2023-06-23 12:16:12.615 DEBUG main runtime::frame-support: ✅ no migration for Treasury    
2023-06-23 12:16:12.615 DEBUG main runtime::frame-support: ✅ no migration for Democracy    
2023-06-23 12:16:12.615 DEBUG main runtime::frame-support: ✅ no migration for Sudo    
2023-06-23 12:16:12.616 DEBUG main runtime::frame-support: ✅ no migration for Dex    
2023-06-23 12:16:12.616 DEBUG main runtime::frame-support: ✅ no migration for AssetRegistry    
2023-06-23 12:16:12.673  INFO main try-runtime::cli: TryRuntime_on_runtime_upgrade executed without errors. Consumed weight = (300000000 ps, 0 byte), total weight = (500000000000 ps, 5242880 byte) (0.06 %, 0.00 %).
```

**Comment by brunopgalvao** [comment]
try-runtime bot has been configured!

Tested here: https://github.com/paritytech/trappist/pull/239

Docs: https://command-bot.parity-prod.parity.io/static/docs/latest.html#link-trappist

**Comment by brunopgalvao** [comment]
We will run the try-runtime bot for releases. Issue complete.
