### ISSUE TITLE
Upgrade to 0.9.42

### ISSUE THREAD

**Issue by valentinfernandez1** [paritytech/trappist#240]
Upgrade Trappist's runtime from v0.9.40 to v0.9.42.

- [x] Upgrade [DEX pallet to v0.9.42](https://github.com/paritytech/substrate-dex/issues/53)
- [x] Consult [Polkadot v0.9.41 + 42 release report](https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-41-v0-9-42/2828) for important changes that may impact Trappist's runtime.
- [x] Upgrade [Chess pallet to polkadot-v0.9.42](https://github.com/SubstrateChess/pallet-chess/issues/29) (Considering its going to be added to Trappist with the next runtime upgrade)
- [x] Upgrade Trappist runtime & node to v0.9.42. See [Parachain template update to v0.9.42 PR](https://github.com/substrate-developer-hub/substrate-parachain-template/pull/158) for guidance.
- [x] Review Runtime config for any misconfigurations.
- [x] Review XCM config for any misconfigurations.
- [x] Update WeightToFee struct to use [FeePolynomial](https://paritytech.github.io/substrate/master/frame_support/weights/struct.FeePolynomial.html) instead of the current custom implementation introduced in #215

**Comment by valentinfernandez1** [comment]
I will be linking any useful links for the upgrade:
**Misc**
[Deprecate Currency; introduce holds and freezing into fungible traits](https://github.com/paritytech/substrate/pull/12951)

**Contracts**
[[Contracts] Overflowing bounded DeletionQueue](
https://github.com/paritytech/substrate/pull/13702)
[Companion PR for contract deletion updates](https://github.com/paritytech/cumulus/pull/2409)

**Comment by valentinfernandez1** [comment]
WIP on branch https://github.com/paritytech/trappist/tree/vf-0.9.42

**Comment by vstam1** [comment]
Looking over the XCM config I have a few points:
- Line 62: Can't we remove Ancestry? Its never used. 
- Line 136: Could use the ConvertedConcreteId instead of ConvertedRegisteredAssetId. I can understand that the name makes more sense then ConvertedConcreteId in this case but could also create seperate `type ConvertedRegisteredAssetId = ConvertedContreteId<...>` to prevent code duplication. I think Gavin did change the trait bounds in 0.9.43 or still just master from Convert -> MaybeEquivalence but think that the 0.9.42 still has the old trait bounds. 
Still just a suggestion, can keep it as is.

- Line 201: Might be able to use RockmineLocation. 

- Line 329: *IMPORTANT*: I would disable random users from sending arbitrary xcm messages to any destination. 

- General: Might be good to change from Rockmine to RococoAssetHub 
- General: Might need to allow teleports from asset hub
